---
- hosts: 172.31.25.80
  become: yes
  tasks:
  - name: i want to execute linux command 
    command: hostname
    register: myresult

  - name: i want to display my 1st task result
    debug:
      msg: "{{myresult}}"

  - name: i want install git
    apt:
      name: git
      state: present
    when: myresult.stderr==""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""