---
- name: add a login tomcat user
  template:
    src:  templates/mytomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: manager context has to change
  template:
    src:  templates/mytommanagercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: host  manager context has to change
  template:
    src:  templates/mytomhostmanagercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml